apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
  namespace: node-gke
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
