name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: react-gke-terraform
  IMAGE: node-express-typescript-k8-gke
  REGISTRY_HOSTNAME: gcr.io
  GKE_CLUSTER_NAME: node-express-typescript-k8-gke
  REGION: europe-west2
  DEPLOYMENT: server-deployment
  CONTAINER_NAME: react-gke-backend-container
  NAMESPACE: node-express-typescript-k8-gke

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 34.98.99.174
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: react-gke-terraform
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - run: |
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region=$REGION
      # Build the Docker image
      - name: Build
        run: |-
          docker build -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:latest" .
      # Push the Docker image to Google Container Registry
      - name: Push
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$IMAGE":latest
      - name: Deploy
        run: |
          kubectl set image deployment/${DEPLOYMENT} ${CONTAINER_NAME}=${REGISTRY_HOSTNAME}/${PROJECT_ID}/${IMAGE}:${GITHUB_SHA} \
          --namespace=${NAMESPACE}
